# Admin site login
admin_username: "admin"
admin_password: "admin"

# Presentation stuf
company_name: "dreamcat4"
company_url: "http://dreamcat4.ath.cx/"
company_logo_path: ""
store_name: "dreamcat4 Store"
copyright_html: "Copyright &copy; 2008 dreamcat4. All rights reserved."
google_analytics_account: ""
include_mint: false
paypal_express_checkout_header_image: "https://secure.dreamcat4.ath.cx/store/images/mylogo.png"

# Google checkout?
allow_google_checkout: true

# Email addresses
support_email: "support@dreamcat4.ath.cx"
sales_email: "sales@dreamcat4.ath.cx"

purchase_receipt_sender_email: "Dreamcat4 <info@dreamcat4.ath.cx>"
purchase_receipt_bcc_email: "orders@dreamcat4.ath.cx"

send_lost_license_sent_notification_email: false
lost_license_sent_notification_sender_email: "Dreamcat4 <support@dreamcat4.ath.cx>"
lost_license_sent_notification_recipient_email: "info@dreamcat4.ath.cx"

crash_report_sender_email: "bugs@dreamcat4.ath.cx"
crash_report_recipient_email: "bugs@dreamcat4.ath.cx"

# Using SSL?
#
# Turning this on redirects most requests that come in through http to https
# In addition, if you're using Apache, you might need to add the following
# to its SSL configuration:
#
#		RequestHeader set X_FORWARDED_PROTO 'https'
#
redirect_to_ssl: true
